[workspace]
resolver = "3"
members = ["earth", "shared-schema", "sky", "end-to-end-test", "maxlen", "maxlen-derive", "rpc", "max-sized-vec"]

[profile.dev.package]
expect-test.opt-level = 3
turmoil.opt-level = 3

[patch.crates-io]
tracing-subscriber = { git = 'https://github.com/zphrs/tracing.git' }
tracing = { git = 'https://github.com/zphrs/tracing.git' }
tracing-core = { git = 'https://github.com/zphrs/tracing.git' }
getrandom4 = { git = 'https://github.com/zphrs/getrandom-twizzler.git', package = 'getrandom', branch = "deterministic-testing" }
getrandom3 = { git = 'https://github.com/zphrs/getrandom-twizzler.git', package = 'getrandom',  branch = "getrandom-v0.2" }
getrandom2 = { git = 'https://github.com/zphrs/getrandom-twizzler.git', package = 'getrandom',  branch = "getrandom-v0.3.5" }

[profile.dev.package.end-to-end-test]
opt-level = 3

[profile.dev.package.rpc]
opt-level = 3

[profile.dev.package.minicbor]
opt-level = 3

[profile.dev.package.kademlia]
opt-level = 3

[profile.dev.package.maxlen]
opt-level = 3


[profile.dev.package.tokio]
opt-level = 3
