[package]
name = "sky"
version = "0.1.0"
edition = "2024"

[dependencies]
max-sized-vec = { version = "0.1.0", path = "../max-sized-vec" }
quinn = { version = "0.11.9", default-features = false, features = ["ring", "bloom", "platform-verifier", "runtime-tokio", "rustls-ring", "futures-io"] }
rpc = { version = "0.1.0", path = "../rpc" }
rustls = { version = "0.23.37", default-features = false, features = ["ring"] }
shared-schema = { version = "0.1.0", path = "../shared-schema" }
tokio = "1.53.1"
tracing = "0.1.44"

[dev-dependencies]
dens = { path = "../dens" }
